version: '3.8'

services:
  app:
    build: .
    container_name: sport_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://ecommerce_user:ecommerce_password@db:5432/ecommerce_db
    ports:
      - "3001:3000"

  db:
    image: postgres:15
    container_name: ecommerce_db
    restart: always
    environment:
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_password
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
